[workspace]
authors = ["Landung 'Don' Setiawan <landungs@uw.edu>"]
channels = ["conda-forge"]
name = "theme-test"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
start = {cmd = "mkdocs serve", description = "Start the MkDocs server for local development."}
gh-deploy = {cmd = "mkdocs gh-deploy --force", description = "Deploy the MkDocs site to GitHub Pages."}

[dependencies]
babel = ">=2.17.0,<3"
colorama = ">=0.4.6,<0.5"
mergedeep = ">=1.3.4,<2"
paginate = ">=0.5.7,<0.6"
regex = ">=2024.11.6,<2025"
requests = ">=2.32.4,<3"
jinja2 = ">=3.1.6,<4"
markdown = ">=3.8.2,<4"
mkdocs = ">=1.6.1,<2"
mkdocs-material-extensions = ">=1.3.1,<2"
pygments = ">=2.19.2,<3"
pymdown-extensions = ">=10.16,<11"
emoji = ">=2.14.1,<3"
mkdocs-material = ">=9.6.15,<10"

[pypi-dependencies]
stepslist = ">=0.7.5, <0.8"

