name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          pixi-version: v0.49.0
          cache: true
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt-get install pngquant 
      - run: pixi run gh-deploy
